apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: jenkins-deployer
rules:
- apiGroups: ["apps"]          # For deployments
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: [""]              # For services
  resources: ["services"]
  verbs: ["get", "create", "update", "patch", "delete"]
